version: "3.7"
services:
    spark-worker:
        image: lasid/spark-worker:latest
        environment:
            - SPARK_MASTER=spark://spark-master:7077
            - SPARK_WORKER_CORES=1
            - SPARK_WORKER_MEMORY=1G
            - SPARK_DRIVER_MEMORY=128m
            - SPARK_EXECUTOR_MEMORY=256m
        expose:
            - 7012
            - 7013
            - 7014
            - 7015
            - 8881
        ports:
            - 8081:8081
        volumes:
            - ./apps:/opt/spark-apps
            - ./data:/opt/spark-data
